FROM armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/node:lts-alpine3.15

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY services/swagger/package.json /usr/src/app

RUN npm install \
&& npm prune \
&& npm cache clean --force

COPY services/swagger /usr/src/app

EXPOSE 3000

CMD [ "npm", "start" ]
